// Generated by gencpp from file solver/Reset.msg
// DO NOT EDIT!


#ifndef SOLVER_MESSAGE_RESET_H
#define SOLVER_MESSAGE_RESET_H

#include <ros/service_traits.h>


#include <solver/ResetRequest.h>
#include <solver/ResetResponse.h>


namespace solver
{

struct Reset
{

typedef ResetRequest Request;
typedef ResetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Reset
} // namespace solver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::solver::Reset > {
  static const char* value()
  {
    return "b60021db68ddc3303a9e21fb2914173c";
  }

  static const char* value(const ::solver::Reset&) { return value(); }
};

template<>
struct DataType< ::solver::Reset > {
  static const char* value()
  {
    return "solver/Reset";
  }

  static const char* value(const ::solver::Reset&) { return value(); }
};


// service_traits::MD5Sum< ::solver::ResetRequest> should match
// service_traits::MD5Sum< ::solver::Reset >
template<>
struct MD5Sum< ::solver::ResetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::solver::Reset >::value();
  }
  static const char* value(const ::solver::ResetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::solver::ResetRequest> should match
// service_traits::DataType< ::solver::Reset >
template<>
struct DataType< ::solver::ResetRequest>
{
  static const char* value()
  {
    return DataType< ::solver::Reset >::value();
  }
  static const char* value(const ::solver::ResetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::solver::ResetResponse> should match
// service_traits::MD5Sum< ::solver::Reset >
template<>
struct MD5Sum< ::solver::ResetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::solver::Reset >::value();
  }
  static const char* value(const ::solver::ResetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::solver::ResetResponse> should match
// service_traits::DataType< ::solver::Reset >
template<>
struct DataType< ::solver::ResetResponse>
{
  static const char* value()
  {
    return DataType< ::solver::Reset >::value();
  }
  static const char* value(const ::solver::ResetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SOLVER_MESSAGE_RESET_H
