// Generated by gencpp from file solver/ResetResponse.msg
// DO NOT EDIT!


#ifndef SOLVER_MESSAGE_RESETRESPONSE_H
#define SOLVER_MESSAGE_RESETRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace solver
{
template <class ContainerAllocator>
struct ResetResponse_
{
  typedef ResetResponse_<ContainerAllocator> Type;

  ResetResponse_()
    : old_count(0)  {
    }
  ResetResponse_(const ContainerAllocator& _alloc)
    : old_count(0)  {
  (void)_alloc;
    }



   typedef int64_t _old_count_type;
  _old_count_type old_count;





  typedef boost::shared_ptr< ::solver::ResetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::solver::ResetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ResetResponse_

typedef ::solver::ResetResponse_<std::allocator<void> > ResetResponse;

typedef boost::shared_ptr< ::solver::ResetResponse > ResetResponsePtr;
typedef boost::shared_ptr< ::solver::ResetResponse const> ResetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::solver::ResetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::solver::ResetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::solver::ResetResponse_<ContainerAllocator1> & lhs, const ::solver::ResetResponse_<ContainerAllocator2> & rhs)
{
  return lhs.old_count == rhs.old_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::solver::ResetResponse_<ContainerAllocator1> & lhs, const ::solver::ResetResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace solver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::solver::ResetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::solver::ResetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::solver::ResetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::solver::ResetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::solver::ResetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::solver::ResetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::solver::ResetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "50d829b83cc38d4dc3e877a949af2705";
  }

  static const char* value(const ::solver::ResetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x50d829b83cc38d4dULL;
  static const uint64_t static_value2 = 0xc3e877a949af2705ULL;
};

template<class ContainerAllocator>
struct DataType< ::solver::ResetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "solver/ResetResponse";
  }

  static const char* value(const ::solver::ResetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::solver::ResetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 old_count\n"
;
  }

  static const char* value(const ::solver::ResetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::solver::ResetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.old_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::solver::ResetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::solver::ResetResponse_<ContainerAllocator>& v)
  {
    s << indent << "old_count: ";
    Printer<int64_t>::stream(s, indent + "  ", v.old_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOLVER_MESSAGE_RESETRESPONSE_H
