// Generated by gencpp from file solver/ResetRequest.msg
// DO NOT EDIT!


#ifndef SOLVER_MESSAGE_RESETREQUEST_H
#define SOLVER_MESSAGE_RESETREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace solver
{
template <class ContainerAllocator>
struct ResetRequest_
{
  typedef ResetRequest_<ContainerAllocator> Type;

  ResetRequest_()
    : new_count(0)  {
    }
  ResetRequest_(const ContainerAllocator& _alloc)
    : new_count(0)  {
  (void)_alloc;
    }



   typedef int64_t _new_count_type;
  _new_count_type new_count;





  typedef boost::shared_ptr< ::solver::ResetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::solver::ResetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetRequest_

typedef ::solver::ResetRequest_<std::allocator<void> > ResetRequest;

typedef boost::shared_ptr< ::solver::ResetRequest > ResetRequestPtr;
typedef boost::shared_ptr< ::solver::ResetRequest const> ResetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::solver::ResetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::solver::ResetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::solver::ResetRequest_<ContainerAllocator1> & lhs, const ::solver::ResetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.new_count == rhs.new_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::solver::ResetRequest_<ContainerAllocator1> & lhs, const ::solver::ResetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace solver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::solver::ResetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::solver::ResetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::solver::ResetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::solver::ResetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::solver::ResetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::solver::ResetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::solver::ResetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d4a4f279878d5dcb73fce49c1644609";
  }

  static const char* value(const ::solver::ResetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d4a4f279878d5dcULL;
  static const uint64_t static_value2 = 0xb73fce49c1644609ULL;
};

template<class ContainerAllocator>
struct DataType< ::solver::ResetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "solver/ResetRequest";
  }

  static const char* value(const ::solver::ResetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::solver::ResetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 new_count\n"
;
  }

  static const char* value(const ::solver::ResetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::solver::ResetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.new_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::solver::ResetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::solver::ResetRequest_<ContainerAllocator>& v)
  {
    s << indent << "new_count: ";
    Printer<int64_t>::stream(s, indent + "  ", v.new_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOLVER_MESSAGE_RESETREQUEST_H
