// Generated by gencpp from file solver/ResetResponse.msg
// DO NOT EDIT!


#ifndef SOLVER_MESSAGE_RESETRESPONSE_H
#define SOLVER_MESSAGE_RESETRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace solver
{
template <class ContainerAllocator>
struct ResetResponse_
{
  typedef ResetResponse_<ContainerAllocator> Type;

  ResetResponse_()
    : old_x(0.0)
    , old_y(0.0)
    , old_yaw(0.0)  {
    }
  ResetResponse_(const ContainerAllocator& _alloc)
    : old_x(0.0)
    , old_y(0.0)
    , old_yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _old_x_type;
  _old_x_type old_x;

   typedef float _old_y_type;
  _old_y_type old_y;

   typedef float _old_yaw_type;
  _old_yaw_type old_yaw;





  typedef boost::shared_ptr< ::solver::ResetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::solver::ResetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ResetResponse_

typedef ::solver::ResetResponse_<std::allocator<void> > ResetResponse;

typedef boost::shared_ptr< ::solver::ResetResponse > ResetResponsePtr;
typedef boost::shared_ptr< ::solver::ResetResponse const> ResetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::solver::ResetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::solver::ResetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::solver::ResetResponse_<ContainerAllocator1> & lhs, const ::solver::ResetResponse_<ContainerAllocator2> & rhs)
{
  return lhs.old_x == rhs.old_x &&
    lhs.old_y == rhs.old_y &&
    lhs.old_yaw == rhs.old_yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::solver::ResetResponse_<ContainerAllocator1> & lhs, const ::solver::ResetResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace solver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::solver::ResetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::solver::ResetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::solver::ResetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::solver::ResetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::solver::ResetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::solver::ResetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::solver::ResetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a7eb1d70d88e6f2247ba417db0eca7f";
  }

  static const char* value(const ::solver::ResetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a7eb1d70d88e6f2ULL;
  static const uint64_t static_value2 = 0x247ba417db0eca7fULL;
};

template<class ContainerAllocator>
struct DataType< ::solver::ResetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "solver/ResetResponse";
  }

  static const char* value(const ::solver::ResetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::solver::ResetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 old_x\n"
"float32 old_y\n"
"float32 old_yaw\n"
;
  }

  static const char* value(const ::solver::ResetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::solver::ResetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.old_x);
      stream.next(m.old_y);
      stream.next(m.old_yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::solver::ResetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::solver::ResetResponse_<ContainerAllocator>& v)
  {
    s << indent << "old_x: ";
    Printer<float>::stream(s, indent + "  ", v.old_x);
    s << indent << "old_y: ";
    Printer<float>::stream(s, indent + "  ", v.old_y);
    s << indent << "old_yaw: ";
    Printer<float>::stream(s, indent + "  ", v.old_yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOLVER_MESSAGE_RESETRESPONSE_H
